---
- name: Worker nodes join the swarm
  shell: docker swarm join --token {{ hostvars.server01.swarm_token_worker.stdout }} --advertise-addr {{ interfaces[ansible_hostname].uplink }} {{interfaces.server01.uplink}}:2377
  

