---
- hosts: spines:leafs
  user: cumulus
  become: yes
  become_method: sudo
  tasks:
    - name: copy interfaces
      copy: src=mlag/{{ansible_hostname}}/interfaces dest=/etc/network
    - name: copy Quagga daemons
      copy: src=mlag/{{ansible_hostname}}/daemons dest=/etc/quagga/
    - name: copy Quagga configuration
      copy: src=mlag/{{ansible_hostname}}/Quagga.conf dest=/etc/quagga/
    - name: reload quagga
      service: name=quagga state=restarted
    - name:  wr the quagga configuration
      command: vtysh -c "wr"
    - name: restarts switches with their new configuration
      shell: sleep 1 && shutdown -r 0
      async: 1
      poll: 0
      ignore_errors: true
    - name: Wait for switches to come back up
      local_action: wait_for port=22 host="{{ inventory_hostname }}" search_regex=OpenSSH delay=10  
      #name: reload networking
      #command: ifreload -a
    #- name: reload quagga
    #  service: name=quagga state=restarted
    #- name:  wr the quagga configuration
    #  command: vtysh -c "wr"
    
- hosts: spines:leafs
  user: cumulus
  become: yes
  become_method: sudo 
  roles:
    - mv_ntp_mgmt_vrf

- hosts: mgmtserver:workerservers
  user: cumulus
  become: yes
  become_method: sudo
  roles:
    - install-docker-ifupdown2
    - ifreload-a-fix
    - install-ifenslave
    - install-bonding-driver

- hosts: mgmtserver:workerservers
  user: cumulus
  become: yes
  become_method: sudo
  tasks:
    - name: copy interfaces
      copy: src=mlag/{{ansible_hostname}}/interfaces dest=/etc/network/
    - name: bring up eth1
      command: ifup eth1
    - name: bring up eth2
      command: ifup eth2
    - name: reload networking
      command:  ifreload -a

- hosts: mgmtserver
  user: cumulus
  become: yes
  become_method: sudo
  roles:
    - initiate-swarm-manager
    - obtain-swarm-token

- hosts: workerservers
  user: cumulus
  become: yes
  become_method: sudo
  roles:
     - join-the-swarm

- hosts: mgmtserver
  user: cumulus
  become: yes
  become_method: sudo
  roles:
     - create-service
